name: easy_dynamic_theme
description: Automatically get your OS defined Theme (Dynamic), force your prefered one (Light / Dark) and persist your choice in the device.
version: 2.0.2
homepage: "https://github.com/rlazom/easy_dynamic_theme"

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  #  Mock library for Dart
  mockito: ^5.0.7